import { LiquidGlassConfig, PresetOption } from "@/types/liquid-glass";

export const DEFAULT_CONFIG: LiquidGlassConfig = {
  name: "Apple VisionOS (Default)",
  presetKey: "visionos",
  navbar: {
    blur: 20,
    saturation: 200,
    frost: 0.1,
    tintColor: "#ffffff",
    tintOpacity: 0.1,
    borderLightColor: "#ffffff",
    borderLightOpacity: 0.4,
    borderDarkColor: "#000000",
    borderDarkOpacity: 0.16,
    sheenEnabled: true,
    sheenIntensity: 0.45,
    ridgeSpecular: true,
    displacementScale: 30,
  },
  global: {
    refractiveIndex: 1.5,
    thickness: 0.8,
    bezelRatio: 0.6,
    saturationBoost: 2.2,
    contrastBoost: 104,
    brightnessBoost: 105,
    chromaticAberration: true,
    dockBlur: 10,
    dockFrost: 0.15,
    buttonBlur: 14,
  },
};

export const PRESET_OPTIONS: PresetOption[] = [
  {
    key: "visionos",
    name: "Apple VisionOS",
    description: "Authentic physics refraction, balanced saturation, and fluid specular shine.",
    accentColor: "#3b82f6",
    config: { ...DEFAULT_CONFIG, name: "Apple VisionOS", presetKey: "visionos" },
  },
  {
    key: "pure-crystal",
    name: "Pure Crystal",
    description: "Ultra-clear refraction with high transmission, sharp rim highlight, and 260% saturation.",
    accentColor: "#06b6d4",
    config: {
      name: "Pure Crystal",
      presetKey: "pure-crystal",
      navbar: {
        blur: 14,
        saturation: 260,
        frost: 0.05,
        tintColor: "#f0f9ff",
        tintOpacity: 0.06,
        borderLightColor: "#ffffff",
        borderLightOpacity: 0.6,
        borderDarkColor: "#0284c7",
        borderDarkOpacity: 0.1,
        sheenEnabled: true,
        sheenIntensity: 0.65,
        ridgeSpecular: true,
        displacementScale: 40,
      },
      global: {
        refractiveIndex: 1.54,
        thickness: 0.95,
        bezelRatio: 0.5,
        saturationBoost: 2.8,
        contrastBoost: 108,
        brightnessBoost: 108,
        chromaticAberration: true,
        dockBlur: 8,
        dockFrost: 0.08,
        buttonBlur: 12,
      },
    },
  },
  {
    key: "frosted-ice",
    name: "Frosted Glacier",
    description: "Deep silky frost with ethereal blue diffusion and soft diffused rim glow.",
    accentColor: "#93c5fd",
    config: {
      name: "Frosted Glacier",
      presetKey: "frosted-ice",
      navbar: {
        blur: 32,
        saturation: 160,
        frost: 0.28,
        tintColor: "#e0f2fe",
        tintOpacity: 0.25,
        borderLightColor: "#ffffff",
        borderLightOpacity: 0.55,
        borderDarkColor: "#0369a1",
        borderDarkOpacity: 0.12,
        sheenEnabled: true,
        sheenIntensity: 0.3,
        ridgeSpecular: false,
        displacementScale: 20,
      },
      global: {
        refractiveIndex: 1.35,
        thickness: 0.6,
        bezelRatio: 0.7,
        saturationBoost: 1.8,
        contrastBoost: 102,
        brightnessBoost: 102,
        chromaticAberration: false,
        dockBlur: 16,
        dockFrost: 0.25,
        buttonBlur: 18,
      },
    },
  },
  {
    key: "cyber-neon",
    name: "Cyber Neon Prism",
    description: "Intense chromatic dispersion with electric cyan sheen and hyper-saturated refraction.",
    accentColor: "#8b5cf6",
    config: {
      name: "Cyber Neon Prism",
      presetKey: "cyber-neon",
      navbar: {
        blur: 18,
        saturation: 320,
        frost: 0.12,
        tintColor: "#c084fc",
        tintOpacity: 0.12,
        borderLightColor: "#e879f9",
        borderLightOpacity: 0.5,
        borderDarkColor: "#6d28d9",
        borderDarkOpacity: 0.25,
        sheenEnabled: true,
        sheenIntensity: 0.8,
        ridgeSpecular: true,
        displacementScale: 45,
      },
      global: {
        refractiveIndex: 1.62,
        thickness: 1.1,
        bezelRatio: 0.55,
        saturationBoost: 3.4,
        contrastBoost: 112,
        brightnessBoost: 110,
        chromaticAberration: true,
        dockBlur: 12,
        dockFrost: 0.16,
        buttonBlur: 16,
      },
    },
  },
  {
    key: "midnight-obsidian",
    name: "Midnight Obsidian",
    description: "Sleek smoked dark glass with platinum catch-lights and deep contrast.",
    accentColor: "#334155",
    config: {
      name: "Midnight Obsidian",
      presetKey: "midnight-obsidian",
      navbar: {
        blur: 24,
        saturation: 150,
        frost: 0.22,
        tintColor: "#0f172a",
        tintOpacity: 0.35,
        borderLightColor: "#94a3b8",
        borderLightOpacity: 0.3,
        borderDarkColor: "#000000",
        borderDarkOpacity: 0.5,
        sheenEnabled: true,
        sheenIntensity: 0.5,
        ridgeSpecular: true,
        displacementScale: 28,
      },
      global: {
        refractiveIndex: 1.48,
        thickness: 0.75,
        bezelRatio: 0.65,
        saturationBoost: 1.6,
        contrastBoost: 115,
        brightnessBoost: 95,
        chromaticAberration: true,
        dockBlur: 14,
        dockFrost: 0.3,
        buttonBlur: 16,
      },
    },
  },
  {
    key: "workwise-signature",
    name: "Work Wise Signature",
    description: "Tuned specifically for Work Wise corporate aesthetic with royal navy glass refraction.",
    accentColor: "#0958a7",
    config: {
      name: "Work Wise Signature",
      presetKey: "workwise-signature",
      navbar: {
        blur: 22,
        saturation: 220,
        frost: 0.12,
        tintColor: "#ffffff",
        tintOpacity: 0.14,
        borderLightColor: "#ffffff",
        borderLightOpacity: 0.5,
        borderDarkColor: "#0958a7",
        borderDarkOpacity: 0.2,
        sheenEnabled: true,
        sheenIntensity: 0.55,
        ridgeSpecular: true,
        displacementScale: 32,
      },
      global: {
        refractiveIndex: 1.52,
        thickness: 0.85,
        bezelRatio: 0.58,
        saturationBoost: 2.4,
        contrastBoost: 105,
        brightnessBoost: 106,
        chromaticAberration: true,
        dockBlur: 12,
        dockFrost: 0.16,
        buttonBlur: 14,
      },
    },
  },
];
