import { LiquidGlassConfig, PresetOption } from "@/types/liquid-glass";

export const DEFAULT_CONFIG: LiquidGlassConfig = {
  name: "Apple VisionOS (Default)",
  presetKey: "visionos",
  navbar: {
    blur: 22,
    saturation: 210,
    frost: 0.1,
    tintColor: "#ffffff",
    tintOpacity: 0.12,
    borderLightColor: "#ffffff",
    borderLightOpacity: 0.5,
    borderDarkColor: "#000000",
    borderDarkOpacity: 0.14,
    sheenEnabled: true,
    sheenIntensity: 0.45,
    ridgeSpecular: true,
    doubleRim: true,
    bounceIntensity: 0.25,
    displacementScale: 38,
    refractionDistance: 42,
    surfaceProfile: "squircle",
    bezelWidth: 26,
    specularAngle: -60,
    specularOpacity: 0.5,
    specularHardness: 14,
    specularSaturation: 4,
    chromaticAberration: true,
    dispersionSpread: 3.5,
    innerShadowBlur: 16,
    innerShadowSpread: 4,
    glassBgTop: "rgba(255,255,255,.13)",
    glassBgBottom: "rgba(255,255,255,.055)",
    glassBorder: "rgba(255,255,255,.42)",
    glassHighlight: "rgba(255,255,255,.68)",
    glassShadow: "rgba(0,0,0,.22)",
    glassBlur: 15,
    glassSat: 145,
    glassBrightness: 1.03,
    glassTint: "rgba(190,220,255,.05)",
    innerDark: "rgba(30,40,55,.045)",
  },
  global: {
    refractiveIndex: 1.52,
    refractionDistance: 45,
    thickness: 0.85,
    bezelRatio: 0.6,
    surfaceProfile: "squircle",
    saturationBoost: 2.3,
    contrastBoost: 104,
    brightnessBoost: 105,
    chromaticAberration: true,
    dispersionSpread: 3.5,
    dockBlur: 12,
    dockFrost: 0.15,
    buttonBlur: 14,
    lightAngle: -60,
    lightElevation: 55,
    specularRoughness: 0.2,
    specularSaturation: 5,
  },
};

export const PRESET_OPTIONS: PresetOption[] = [
  {
    key: "clear",
    name: "Ultra Clear",
    description: "Maximum optical clarity, low blur, subtle highlight, and natural high light transmission.",
    accentColor: "#38bdf8",
    config: {
      ...DEFAULT_CONFIG,
      name: "Ultra Clear",
      presetKey: "clear",
      navbar: {
        ...DEFAULT_CONFIG.navbar,
        blur: 10,
        saturation: 145,
        displacementScale: 28,
        refractionDistance: 38,
        glassBgTop: "rgba(255,255,255,.10)",
        glassBgBottom: "rgba(255,255,255,.025)",
        glassBorder: "rgba(255,255,255,.36)",
        glassHighlight: "rgba(255,255,255,.68)",
        glassShadow: "rgba(0,0,0,.19)",
        glassBlur: 10,
        glassSat: 145,
        glassBrightness: 1.03,
        glassTint: "rgba(170,215,255,.035)",
        innerDark: "rgba(30,40,55,.03)",
      },
      global: {
        ...DEFAULT_CONFIG.global,
        refractiveIndex: 1.5,
        contrastBoost: 103,
        brightnessBoost: 103,
      },
    },
  },
  {
    key: "crystal",
    name: "Crystal",
    description: "Crisp optical density with luminous highlights and high refraction transmission.",
    accentColor: "#06b6d4",
    config: {
      ...DEFAULT_CONFIG,
      name: "Crystal",
      presetKey: "crystal",
      navbar: {
        ...DEFAULT_CONFIG.navbar,
        blur: 16,
        saturation: 160,
        displacementScale: 40,
        refractionDistance: 44,
        glassBgTop: "rgba(255,255,255,.16)",
        glassBgBottom: "rgba(255,255,255,.045)",
        glassBorder: "rgba(255,255,255,.50)",
        glassHighlight: "rgba(255,255,255,.85)",
        glassShadow: "rgba(0,0,0,.22)",
        glassBlur: 16,
        glassSat: 160,
        glassBrightness: 1.06,
        glassTint: "rgba(180,225,255,.07)",
        innerDark: "rgba(20,30,45,.045)",
      },
      global: {
        ...DEFAULT_CONFIG.global,
        refractiveIndex: 1.58,
        contrastBoost: 105,
        brightnessBoost: 106,
      },
    },
  },
  {
    key: "frost",
    name: "Soft Frost",
    description: "Deep diffuse frost with frosted texture, gentle luminescence, and diffused highlights.",
    accentColor: "#93c5fd",
    config: {
      ...DEFAULT_CONFIG,
      name: "Soft Frost",
      presetKey: "frost",
      navbar: {
        ...DEFAULT_CONFIG.navbar,
        blur: 31,
        saturation: 125,
        displacementScale: 18,
        refractionDistance: 24,
        glassBgTop: "rgba(255,255,255,.24)",
        glassBgBottom: "rgba(255,255,255,.11)",
        glassBorder: "rgba(255,255,255,.55)",
        glassHighlight: "rgba(255,255,255,.73)",
        glassShadow: "rgba(0,0,0,.20)",
        glassBlur: 31,
        glassSat: 125,
        glassBrightness: 1.08,
        glassTint: "rgba(220,235,255,.07)",
        innerDark: "rgba(25,35,45,.025)",
      },
      global: {
        ...DEFAULT_CONFIG.global,
        refractiveIndex: 1.35,
        contrastBoost: 102,
        brightnessBoost: 108,
      },
    },
  },
  {
    key: "smoke",
    name: "Smoke",
    description: "Smoky dark tinted glass with deep contrast, moody shading, and platinum specular.",
    accentColor: "#64748b",
    config: {
      ...DEFAULT_CONFIG,
      name: "Smoke",
      presetKey: "smoke",
      navbar: {
        ...DEFAULT_CONFIG.navbar,
        blur: 18,
        saturation: 135,
        displacementScale: 28,
        refractionDistance: 32,
        glassBgTop: "rgba(35,38,45,.34)",
        glassBgBottom: "rgba(8,10,15,.20)",
        glassBorder: "rgba(255,255,255,.22)",
        glassHighlight: "rgba(255,255,255,.50)",
        glassShadow: "rgba(0,0,0,.38)",
        glassBlur: 18,
        glassSat: 135,
        glassBrightness: 0.88,
        glassTint: "rgba(100,125,170,.07)",
        innerDark: "rgba(0,0,0,.11)",
      },
      global: {
        ...DEFAULT_CONFIG.global,
        refractiveIndex: 1.48,
        contrastBoost: 115,
        brightnessBoost: 88,
      },
    },
  },
  {
    key: "prism",
    name: "Prismatic",
    description: "Hyper-saturated dispersion with vibrant magenta-cyan iridescent reflection.",
    accentColor: "#c084fc",
    config: {
      ...DEFAULT_CONFIG,
      name: "Prismatic",
      presetKey: "prism",
      navbar: {
        ...DEFAULT_CONFIG.navbar,
        blur: 13,
        saturation: 190,
        displacementScale: 50,
        refractionDistance: 60,
        glassBgTop: "rgba(255,255,255,.115)",
        glassBgBottom: "rgba(255,255,255,.025)",
        glassBorder: "rgba(255,255,255,.45)",
        glassHighlight: "rgba(255,255,255,.78)",
        glassShadow: "rgba(0,0,0,.20)",
        glassBlur: 13,
        glassSat: 190,
        glassBrightness: 1.07,
        glassTint: "rgba(210,130,255,.12)",
        innerDark: "rgba(20,30,50,.035)",
      },
      global: {
        ...DEFAULT_CONFIG.global,
        refractiveIndex: 1.66,
        contrastBoost: 108,
        brightnessBoost: 107,
      },
    },
  },
  {
    key: "lens",
    name: "Deep Lens",
    description: "Optical concave lens curvature with intense specular caustic and crisp clarity.",
    accentColor: "#3b82f6",
    config: {
      ...DEFAULT_CONFIG,
      name: "Deep Lens",
      presetKey: "lens",
      navbar: {
        ...DEFAULT_CONFIG.navbar,
        blur: 8,
        saturation: 160,
        displacementScale: 62,
        refractionDistance: 70,
        glassBgTop: "rgba(255,255,255,.07)",
        glassBgBottom: "rgba(255,255,255,.018)",
        glassBorder: "rgba(255,255,255,.44)",
        glassHighlight: "rgba(255,255,255,.94)",
        glassShadow: "rgba(0,0,0,.27)",
        glassBlur: 8,
        glassSat: 160,
        glassBrightness: 1.05,
        glassTint: "rgba(140,205,255,.05)",
        innerDark: "rgba(10,20,35,.075)",
      },
      global: {
        ...DEFAULT_CONFIG.global,
        refractiveIndex: 1.68,
        contrastBoost: 106,
        brightnessBoost: 105,
      },
    },
  },
  {
    key: "visionos",
    name: "Apple VisionOS",
    description: "Authentic physics refraction, balanced saturation, and fluid squircle specular shine.",
    accentColor: "#3b82f6",
    config: { ...DEFAULT_CONFIG, name: "Apple VisionOS", presetKey: "visionos" },
  },
  {
    key: "macos-sequoia",
    name: "macOS Sequoia",
    description: "Ultra-crisp floating glass capsule with sharp specular rim and refined optical transmission.",
    accentColor: "#6366f1",
    config: {
      name: "macOS Sequoia",
      presetKey: "macos-sequoia",
      navbar: {
        blur: 24,
        saturation: 190,
        frost: 0.08,
        tintColor: "#ffffff",
        tintOpacity: 0.15,
        borderLightColor: "#ffffff",
        borderLightOpacity: 0.65,
        borderDarkColor: "#0f172a",
        borderDarkOpacity: 0.12,
        sheenEnabled: true,
        sheenIntensity: 0.5,
        ridgeSpecular: true,
        doubleRim: true,
        bounceIntensity: 0.35,
        displacementScale: 32,
        refractionDistance: 38,
        surfaceProfile: "squircle",
        bezelWidth: 24,
        specularAngle: -45,
        specularOpacity: 0.6,
        specularHardness: 18,
        specularSaturation: 3.5,
        chromaticAberration: true,
        dispersionSpread: 2.8,
        innerShadowBlur: 14,
        innerShadowSpread: 3,
      },
      global: {
        refractiveIndex: 1.5,
        refractionDistance: 40,
        thickness: 0.8,
        bezelRatio: 0.55,
        surfaceProfile: "squircle",
        saturationBoost: 2.0,
        contrastBoost: 103,
        brightnessBoost: 104,
        chromaticAberration: true,
        dispersionSpread: 2.5,
        dockBlur: 14,
        dockFrost: 0.14,
        buttonBlur: 12,
        lightAngle: -45,
        lightElevation: 60,
        specularRoughness: 0.18,
        specularSaturation: 4,
      },
    },
  },
  {
    key: "ios-fluid",
    name: "iOS 18 Fluid Glass",
    description: "Dynamic fluid material with high elasticity, deep color magnification, and responsive specular sheen.",
    accentColor: "#ec4899",
    config: {
      name: "iOS 18 Fluid Glass",
      presetKey: "ios-fluid",
      navbar: {
        blur: 18,
        saturation: 240,
        frost: 0.07,
        tintColor: "#ffffff",
        tintOpacity: 0.14,
        borderLightColor: "#ffffff",
        borderLightOpacity: 0.7,
        borderDarkColor: "#000000",
        borderDarkOpacity: 0.18,
        sheenEnabled: true,
        sheenIntensity: 0.7,
        ridgeSpecular: true,
        doubleRim: true,
        bounceIntensity: 0.3,
        displacementScale: 46,
        refractionDistance: 55,
        surfaceProfile: "squircle",
        bezelWidth: 30,
        specularAngle: -70,
        specularOpacity: 0.65,
        specularHardness: 16,
        specularSaturation: 5,
        chromaticAberration: true,
        dispersionSpread: 4.5,
        innerShadowBlur: 18,
        innerShadowSpread: 5,
      },
      global: {
        refractiveIndex: 1.58,
        refractionDistance: 50,
        thickness: 0.95,
        bezelRatio: 0.65,
        surfaceProfile: "squircle",
        saturationBoost: 2.6,
        contrastBoost: 106,
        brightnessBoost: 107,
        chromaticAberration: true,
        dispersionSpread: 4.0,
        dockBlur: 10,
        dockFrost: 0.12,
        buttonBlur: 16,
        lightAngle: -70,
        lightElevation: 50,
        specularRoughness: 0.15,
        specularSaturation: 6,
      },
    },
  },
  {
    key: "pure-crystal",
    name: "Pure Crystal",
    description: "Ultra-clear refraction with high transmission, sharp rim highlight, and 260% saturation.",
    accentColor: "#06b6d4",
    config: {
      name: "Pure Crystal",
      presetKey: "pure-crystal",
      navbar: {
        blur: 14,
        saturation: 260,
        frost: 0.04,
        tintColor: "#f0f9ff",
        tintOpacity: 0.06,
        borderLightColor: "#ffffff",
        borderLightOpacity: 0.75,
        borderDarkColor: "#0284c7",
        borderDarkOpacity: 0.1,
        sheenEnabled: true,
        sheenIntensity: 0.65,
        ridgeSpecular: true,
        doubleRim: true,
        bounceIntensity: 0.4,
        displacementScale: 52,
        refractionDistance: 65,
        surfaceProfile: "circle",
        bezelWidth: 32,
        specularAngle: -55,
        specularOpacity: 0.75,
        specularHardness: 24,
        specularSaturation: 5,
        chromaticAberration: true,
        dispersionSpread: 5.0,
        innerShadowBlur: 12,
        innerShadowSpread: 3,
      },
      global: {
        refractiveIndex: 1.65,
        refractionDistance: 60,
        thickness: 1.05,
        bezelRatio: 0.5,
        surfaceProfile: "circle",
        saturationBoost: 2.8,
        contrastBoost: 108,
        brightnessBoost: 108,
        chromaticAberration: true,
        dispersionSpread: 4.8,
        dockBlur: 8,
        dockFrost: 0.06,
        buttonBlur: 12,
        lightAngle: -55,
        lightElevation: 65,
        specularRoughness: 0.1,
        specularSaturation: 6,
      },
    },
  },
  {
    key: "frosted-ice",
    name: "Frosted Glacier",
    description: "Deep silky frost with ethereal blue diffusion and soft diffused rim glow.",
    accentColor: "#93c5fd",
    config: {
      name: "Frosted Glacier",
      presetKey: "frosted-ice",
      navbar: {
        blur: 32,
        saturation: 160,
        frost: 0.28,
        tintColor: "#e0f2fe",
        tintOpacity: 0.25,
        borderLightColor: "#ffffff",
        borderLightOpacity: 0.55,
        borderDarkColor: "#0369a1",
        borderDarkOpacity: 0.12,
        sheenEnabled: true,
        sheenIntensity: 0.3,
        ridgeSpecular: false,
        doubleRim: false,
        bounceIntensity: 0.15,
        displacementScale: 20,
        refractionDistance: 25,
        surfaceProfile: "squircle",
        bezelWidth: 20,
        specularAngle: -60,
        specularOpacity: 0.3,
        specularHardness: 6,
        specularSaturation: 2,
        chromaticAberration: false,
        dispersionSpread: 1.5,
        innerShadowBlur: 22,
        innerShadowSpread: 6,
      },
      global: {
        refractiveIndex: 1.35,
        refractionDistance: 25,
        thickness: 0.6,
        bezelRatio: 0.7,
        surfaceProfile: "squircle",
        saturationBoost: 1.8,
        contrastBoost: 102,
        brightnessBoost: 102,
        chromaticAberration: false,
        dispersionSpread: 1.0,
        dockBlur: 16,
        dockFrost: 0.25,
        buttonBlur: 18,
        lightAngle: -60,
        lightElevation: 45,
        specularRoughness: 0.45,
        specularSaturation: 2,
      },
    },
  },
  {
    key: "cyber-neon",
    name: "Cyber Neon Prism",
    description: "Intense chromatic dispersion with electric cyan sheen and hyper-saturated refraction.",
    accentColor: "#8b5cf6",
    config: {
      name: "Cyber Neon Prism",
      presetKey: "cyber-neon",
      navbar: {
        blur: 18,
        saturation: 320,
        frost: 0.12,
        tintColor: "#c084fc",
        tintOpacity: 0.14,
        borderLightColor: "#e879f9",
        borderLightOpacity: 0.6,
        borderDarkColor: "#6d28d9",
        borderDarkOpacity: 0.25,
        sheenEnabled: true,
        sheenIntensity: 0.85,
        ridgeSpecular: true,
        doubleRim: true,
        bounceIntensity: 0.45,
        displacementScale: 58,
        refractionDistance: 70,
        surfaceProfile: "lip",
        bezelWidth: 34,
        specularAngle: -45,
        specularOpacity: 0.8,
        specularHardness: 22,
        specularSaturation: 7,
        chromaticAberration: true,
        dispersionSpread: 7.5,
        innerShadowBlur: 18,
        innerShadowSpread: 5,
      },
      global: {
        refractiveIndex: 1.68,
        refractionDistance: 68,
        thickness: 1.15,
        bezelRatio: 0.55,
        surfaceProfile: "lip",
        saturationBoost: 3.4,
        contrastBoost: 112,
        brightnessBoost: 110,
        chromaticAberration: true,
        dispersionSpread: 7.0,
        dockBlur: 12,
        dockFrost: 0.16,
        buttonBlur: 16,
        lightAngle: -45,
        lightElevation: 50,
        specularRoughness: 0.12,
        specularSaturation: 7,
      },
    },
  },
  {
    key: "midnight-obsidian",
    name: "Midnight Obsidian",
    description: "Sleek smoked dark glass with platinum catch-lights and deep contrast.",
    accentColor: "#334155",
    config: {
      name: "Midnight Obsidian",
      presetKey: "midnight-obsidian",
      navbar: {
        blur: 24,
        saturation: 150,
        frost: 0.22,
        tintColor: "#0f172a",
        tintOpacity: 0.35,
        borderLightColor: "#94a3b8",
        borderLightOpacity: 0.35,
        borderDarkColor: "#000000",
        borderDarkOpacity: 0.55,
        sheenEnabled: true,
        sheenIntensity: 0.5,
        ridgeSpecular: true,
        doubleRim: true,
        bounceIntensity: 0.25,
        displacementScale: 28,
        refractionDistance: 32,
        surfaceProfile: "squircle",
        bezelWidth: 22,
        specularAngle: -60,
        specularOpacity: 0.5,
        specularHardness: 16,
        specularSaturation: 2.5,
        chromaticAberration: true,
        dispersionSpread: 2.5,
        innerShadowBlur: 24,
        innerShadowSpread: 6,
      },
      global: {
        refractiveIndex: 1.48,
        refractionDistance: 35,
        thickness: 0.75,
        bezelRatio: 0.65,
        surfaceProfile: "squircle",
        saturationBoost: 1.6,
        contrastBoost: 115,
        brightnessBoost: 95,
        chromaticAberration: true,
        dispersionSpread: 2.5,
        dockBlur: 14,
        dockFrost: 0.3,
        buttonBlur: 16,
        lightAngle: -60,
        lightElevation: 55,
        specularRoughness: 0.25,
        specularSaturation: 3,
      },
    },
  },
  {
    key: "workwise-signature",
    name: "Work Wise Signature",
    description: "Tuned specifically for Work Wise corporate aesthetic with royal navy glass refraction.",
    accentColor: "#0958a7",
    config: {
      name: "Work Wise Signature",
      presetKey: "workwise-signature",
      navbar: {
        blur: 22,
        saturation: 220,
        frost: 0.12,
        tintColor: "#ffffff",
        tintOpacity: 0.14,
        borderLightColor: "#ffffff",
        borderLightOpacity: 0.55,
        borderDarkColor: "#0958a7",
        borderDarkOpacity: 0.2,
        sheenEnabled: true,
        sheenIntensity: 0.55,
        ridgeSpecular: true,
        doubleRim: true,
        bounceIntensity: 0.3,
        displacementScale: 36,
        refractionDistance: 45,
        surfaceProfile: "squircle",
        bezelWidth: 28,
        specularAngle: -60,
        specularOpacity: 0.55,
        specularHardness: 15,
        specularSaturation: 4.5,
        chromaticAberration: true,
        dispersionSpread: 3.5,
        innerShadowBlur: 16,
        innerShadowSpread: 4,
      },
      global: {
        refractiveIndex: 1.54,
        refractionDistance: 46,
        thickness: 0.88,
        bezelRatio: 0.58,
        surfaceProfile: "squircle",
        saturationBoost: 2.4,
        contrastBoost: 105,
        brightnessBoost: 106,
        chromaticAberration: true,
        dispersionSpread: 3.5,
        dockBlur: 12,
        dockFrost: 0.16,
        buttonBlur: 14,
        lightAngle: -60,
        lightElevation: 55,
        specularRoughness: 0.2,
        specularSaturation: 5,
      },
    },
  },
];
